name:                VC
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/VC#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2023 Author name here
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6.5.1
  - exceptions >= 0.10.4
  - bytestring
  - array
  - hashable
  - directory >= 1.3.6.2
  - process >= 1.6.16.0
  - transformers >= 0.5.6.2
  - filepath
  - relude
  - algebraic-graphs
  - mtl
  - regex-compat >=0.95.2.1
  - extra
  - split

build-tools:
  - alex
  - happy

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing


executables:
  vc:
    source-dirs:      src
    main:             Main.hs
    other-modules:
      - Lean
      - Lexer
      - Parser
      - Preprocessor
      - PrimOps
      - ProofGenerator
      - Properties
      - Types
      - Utils
