name: Build

on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.0
      - name: The Determinate Nix Installer
        uses: DeterminateSystems/nix-installer-action@v14
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Cache Lean toolchain
        uses: actions/cache@v4.1.0
        with:
          path: ~/.elan/toolchains
          key: ${{ runner.os }}-lean-toolchain-${{ hashFiles('lean-toolchain') }}
      - name: Cache Lean packages
        uses: actions/cache@v4.1.0
        with:
          path: .lake/packages
          key: ${{ runner.os }}-lean-packages-${{ hashFiles('lake-manifest.json') }}
      - name: Retrieve or restore flake.nix build inputs
        run: nix develop
      - name: Build vc tool
        run: nix develop --command bash -c "cd vc; stack --nix build"
      - name: Build Lean files
        run: nix develop --command bash -c "lake build"
